[build-system]
requires = ["setuptools", "wheel"]

[tool.poetry.dependencies]
# ...existing code...
shapely = { version = "*", allow-prereleases = true, extras = ["--no-binary shapely"] }
tiktoken = { version = "*", allow-prereleases = true, extras = ["--no-binary tiktoken"] }
# ...existing code...